### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by jackton1**
@olance

### CODE REVIEW

**Comment by minchinweb** [comment]
👍 I'm getting an error when I try and run the action, and <del>I think</del> this would fix it. Here's the error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/entrypoint.sh": permission denied: unknown

**Comment by olance** [comment]
Damn sometimes I publish stuff and forget I did or don't realize others are using it 🙈

Looking into this now!

**Comment by olance** [comment]
Thanks @jackton1 for this fix and sorry it escaped my attention :(

**Comment by minchinweb** [comment]
@olance All good; glad to see an update! Thanks!

**Pull request merged**
